# -*- coding: utf-8 -*-
"""Fine Tuning for content filteration model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cZCR52IrzjCJtUm_LM7ytpAAbhSIHly8
"""

!pip install transformers==5.0.0 datasets accelerate -q

from datasets import load_dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
    pipeline
)
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

dataset = load_dataset("IbrahimAmin/egyptian-arabic-hate-speech")

num_labels = 5
model_name = "UBC-NLP/MARBERT"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels
)

unique_labels = sorted(dataset["train"].unique("label"))
label2id = {label: i for i, label in enumerate(unique_labels)}
id2label = {i: label for label, i in label2id.items()}

print("Label mapping:", label2id)

def convert_labels(example):
    example['label'] = label2id[example['label']]
    return example

dataset = dataset.map(convert_labels)

model.config.label2id = label2id
model.config.id2label = id2label
model.config.num_labels = num_labels

def tokenize_function(example):
    return tokenizer(example["text"], padding="max_length", truncation=True)

tokenized_datasets = dataset.map(tokenize_function, batched=True)

import pandas as pd
pd.Series(dataset['train']['label']).value_counts()

import pandas as pd
pd.Series(dataset['test']['label']).value_counts()

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    precision, recall, f1, _ = precision_recall_fscore_support(labels, preds, average='weighted')
    acc = accuracy_score(labels, preds)
    return {
        "accuracy": acc,
        "f1": f1,
        "precision": precision,
        "recall": recall,
    }

training_args = TrainingArguments(
    output_dir="./filter_content_model",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=5,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=100,
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    processing_class=tokenizer,
    compute_metrics=compute_metrics,
)

trainer.train()

trainer.save_model("./filter_content_model")
tokenizer.save_pretrained("./filter_content_model")

metrics = trainer.evaluate()
print(metrics)

sentiment_analyzer = pipeline("text-classification", model="CAMeL-Lab/bert-base-arabic-camelbert-da-sentiment")





